=== rushioda/PIXELVALID_athena/athena/TileCalorimeter/TileG4/TileAncillary/LarCrate/share/material.dtd
<?xml encoding="ISO-8859-1"?>

<!-- @version: -->

<!ELEMENT FADS (element*|composite*)+>

<!ELEMENT  element  EMPTY>
<!ATTLIST  element 
           symbol    CDATA  #IMPLIED
           name      ID     #REQUIRED
           z         CDATA  #REQUIRED
           aweight   CDATA  #REQUIRED
           density   CDATA  #IMPLIED
		   radlenght CDATA  #IMPLIED>
	   
<!ELEMENT  composite ( addmaterial)+>
<!ATTLIST  composite
           name     ID     #REQUIRED
           density  CDATA  #REQUIRED
		   radlenght CDATA  #IMPLIED>

<!ELEMENT  addmaterial  ( fractionmass | natoms ) >
<!ATTLIST  addmaterial
           material     CDATA  #REQUIRED
>

<!ELEMENT fractionmass EMPTY>
<!ATTLIST fractionmass
          fraction      CDATA #REQUIRED
>

<!ELEMENT natoms EMPTY>
<!ATTLIST natoms
          n             CDATA #REQUIRED
>

=== rushioda/PIXELVALID_athena/athena/TileCalorimeter/TileG4/TileAncillary/LarCrate/share/LArCrate_materials.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE FADS SYSTEM "material.dtd">

<FADS>

<!-- Air -->
  <composite  name="TileAir" density="0.00129">
    <addmaterial material="Nitrogen"> <fractionmass fraction="0.7494"/> </addmaterial>
    <addmaterial material="Oxygen"> <fractionmass fraction="0.2369"/> </addmaterial>
    <addmaterial material="Argon"> <fractionmass fraction="0.0129"/> </addmaterial>
    <addmaterial material="Hydrogen"> <fractionmass fraction="0.0008"/> </addmaterial>
  </composite>

<!-- Material in crate --> 
  <composite  name="LArCrateMaterial" density="0.2876">
    <addmaterial material="Aluminum"> <fractionmass fraction="0.7744"/></addmaterial>
    <addmaterial material="SiO2CondEpox"> <fractionmass fraction="0.2216"/> </addmaterial>
    <addmaterial material="TileAir"> <fractionmass fraction="0.0040"/> </addmaterial>
  </composite> 

</FADS>
