=== rushioda/PIXELVALID_athena/athena/Tools/RunTimeTester/share/web/RTT.dtd
<!ELEMENT rttconfig (mode,                release,             refRelease,  
                     cmtConfig,           branch,              runType,
                     topProject,          otherProject?,       distArea,
                     workBasePath,        resultsBasePath,     resultsBaseURL,
                     site,                dataSetCatalog,      jobGroupConfig,    
                     pathToVetoFile?,     dCubeCfgFile?,    
                     refDB?,              moniDB?,             confFileSrc, 
                     packageAccept*,      packageVeto*,        webpageBranchVeto*,
                     testMode?,           maxTime?,            versionDir?,  
                     libToolsLoc?,        confFileSuffix?,
                     rttKitTest?,         releaseType?,        rttPilotJobs?,
                     atnPilotJobs?,       concurrent?,         disableMailTo?,    devRun?, 
                     deleteNonKeepFiles?, bigFiles?)>
    
   <!ELEMENT mode                   (#PCDATA)>
   <!ELEMENT release                (#PCDATA)>
   <!ELEMENT refRelease             (#PCDATA)>
   <!ELEMENT cmtConfig              (#PCDATA)>
   <!ELEMENT branch                 (#PCDATA)>
   <!ELEMENT runType                (releaseRun | kitRun)>
   <!ELEMENT topProject             (#PCDATA)>  
   <!ELEMENT otherProject           (#PCDATA)>  
   <!ELEMENT distArea               (#PCDATA)>
   <!ELEMENT workBasePath           (#PCDATA)>
   <!ELEMENT resultsBasePath        (#PCDATA)>
   <!ELEMENT resultsBaseURL         (#PCDATA)>
   <!ELEMENT site                   (#PCDATA)>
   <!ELEMENT dataSetCatalog         (#PCDATA)>
   <!ELEMENT jobGroupConfig         (#PCDATA)>
   <!ELEMENT pathToVetoFile         (#PCDATA)>
   <!ELEMENT dCubeCfgFile           (#PCDATA)>
   <!ELEMENT confFileSrc            (  (rttProvides,  
                                         localConfFiles?, 
                                         installedConfFiles?) |
                                       (rttProvides?, 
                                         localConfFiles,  
                                         installedConfFiles?) |
                                       (rttProvides?, 
                                         localConfFiles?, 
                                         installedConfFiles) )>

   <!ELEMENT releaseRun             EMPTY>
   <!ELEMENT kitRun                 (installArea)>
   <!ELEMENT installArea            (#PCDATA)>
   <!ELEMENT rttProvides            (packageConfFile+)>
      <!ELEMENT packageConfFile     (package, pathToFile, cmtpath, version,
                                     installArea, shareArea)>
         <!ELEMENT package          (#PCDATA)>
         <!ELEMENT pathToFile       (#PCDATA)>
         <!ELEMENT cmtpath          (#PCDATA)>
         <!ELEMENT version          (#PCDATA)>
         <!ELEMENT shareArea        (#PCDATA)>
   <!ELEMENT localConfFiles         (userHomeCmtDir, testProjectCmtDir)>
   <!ELEMENT installedConfFiles     EMPTY>
   <!ELEMENT refDB                  (file, enable)>
      <!ELEMENT file                (#PCDATA)>
      <!ELEMENT enable              (#PCDATA)>
   <!ELEMENT moniDB                 (file, enable)>
   <!ELEMENT packageAccept          (#PCDATA)>
   <!ELEMENT packageVeto            (#PCDATA)>
   <!ELEMENT webpageBranchVeto      (#PCDATA)>
   <!ELEMENT testMode               (#PCDATA)>
   <!ELEMENT maxTime                ((hours, minutes?) | minutes)>
      <!ELEMENT hours               (#PCDATA)>
      <!ELEMENT minutes             (#PCDATA)>
   <!ELEMENT versionDir             (#PCDATA)>
   <!ELEMENT libToolsLoc            (#PCDATA)>
   <!ELEMENT confFileSuffix         (#PCDATA)>
   <!ELEMENT rttKitTest             EMPTY>   
   <!ELEMENT releaseType            (#PCDATA)> 
   <!ELEMENT rttPilotJobs               EMPTY>
   <!ELEMENT atnPilotJobs               EMPTY>
   <!ELEMENT userHomeCmtDir         (#PCDATA)> 
   <!ELEMENT testProjectCmtDir      (#PCDATA)> 
  <!ELEMENT concurrent             (wpcServer)>
     <!ELEMENT wpcServer            (#PCDATA)>
   <!ELEMENT disableMailTo              EMPTY>
   <!ELEMENT devRun                     EMPTY>
   <!ELEMENT deleteNonKeepFiles         EMPTY>
   <!ELEMENT bigFiles               (bigFilesArea, bigFilesSize)>
   <!ELEMENT bigFilesArea           (#PCDATA)>
   <!ELEMENT bigFilesSize           (#PCDATA)>

=== rushioda/PIXELVALID_athena/athena/Tools/RunTimeTester/src/TestSuiteFixtures/Fixtures1/cfg/rttUnitTests.xml
<?xml version="1.0"?>


<!DOCTYPE rttconfig SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/RTT.dtd"> 

<!-- <!DOCTYPE rttconfig SYSTEM "file:///Users/peter/RTTtop/DTD/RTT.dtd"> -->

<rttconfig>
   <mode>PBS</mode>
   <release>11.3.0</release>
   <refRelease>11.0.0</refRelease>
   <build>opt</build>
   <branch>N.X.0</branch>
   <runType>
      <releaseRun/>
   </runType>
   <workBasePath>TESTSUITESCRATCH/Work</workBasePath>
   <resultsBasePath>TESTSUITESCRATCH/Results</resultsBasePath>
   <site>CERN</site>
   <dataSetCatalog>TESTSUITESCRATCH/xml/rttUnitTestDataSetCatalog.xml</dataSetCatalog>
   <jobGroupConfig>TESTSUITESCRATCH/xml/rttUnitTestTopLevelJobGroup.xml</jobGroupConfig>
   <refDB>
      <file>TESTSUITESCRATCH/rttUnitTestRefFile.db</file>
      <enable>1</enable>
   </refDB>
   <moniDB>
      <file>TESTSUITESCRATCH/rttUnitTestMoniFile.db</file>
      <enable>1</enable>
   </moniDB>


   <confFileSrc>
      <rttProvides>
        <packageConfFile>
           <package>Simulation/Atlfast/TestAtlfast</package>
           <pathToFile>TESTSUITESCRATCH/xml/TestAtlfast_TestConfiguration.xml</pathToFile>

           <cmtpath>/afs/cern.ch/atlas/software/builds/AtlasReconstruction/1.3.0</cmtpath>
           <version>TestAtlfast-00-00-61</version>
           <installArea>/afs/cern.ch/atlas/software/builds/AtlasReconstruction/1.3.0/InstallArea</installArea>

           <shareArea>/afs/cern.ch/atlas/software/builds/AtlasReconstruction/1.3.0/InstallArea/share</shareArea>
        </packageConfFile>


        <packageConfFile>
           <package>Tools/RunTimeTester</package>
           <pathToFile>TESTSUITESCRATCH/xml/RunTimeTester_TestConfiguration.xml</pathToFile>

           <cmtpath>/afs/cern.ch/atlas/software/builds/AtlasCore/1.3.0</cmtpath>
           <version>RunTimeTester-00-00-82</version>
           <installArea>/afs/cern.ch/atlas/software/builds/AtlasCore/1.3.0/InstallArea</installArea>

           <shareArea>/afs/cern.ch/atlas/software/builds/AtlasCore/1.3.0/InstallArea/share</shareArea>
        </packageConfFile>


      </rttProvides>
      <installedConfFiles/>
   </confFileSrc>

   <!-- <packageAccept>HelloWorld</packageAccept> -->
   <!-- <packageVeto>TestAtlfast</packageVeto> -->
<!--   <testMode>NoNewRunDirs</testMode> -->
   <maxTime>
      <hours>1</hours>
   </maxTime>
   <!-- <rttKitTest/> -->
   <releaseType>project</releaseType>
</rttconfig>

=== rushioda/PIXELVALID_athena/athena/Tools/RunTimeTester/src/TestSuiteFixtures/cfg/rttUnitTests.xml
<?xml version="1.0"?>


<!DOCTYPE rttconfig SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/RTT.dtd">


<!-- <!DOCTYPE rttconfig SYSTEM "RTT.dtd"> -->
<rttconfig>
   <mode>PBS</mode>
   <release>11.0.0</release>
   <refRelease>11.0.0</refRelease>
   <build>opt</build>
   <branch>N.X.0</branch>
   <workBasePath>TESTSUITESCRATCH/Work</workBasePath>
   <resultsBasePath>TESTSUITESCRATCH/Results</resultsBasePath>
   <site>CERN</site>
   <dataSetCatalog>TESTSUITESCRATCH/xml/rttUnitTestDataSetCatalog.xml</dataSetCatalog>
   <jobGroupConfig>TESTSUITESCRATCH/xml/rttUnitTestTopLevelJobGroup.xml</jobGroupConfig>
   <refDB>
      <file>TESTSUITESCRATCH/rttUnitTestRefFile.db</file>
      <enable>1</enable>
   </refDB>


   <confFileSrc>
      <rttProvides>
        <!-- <packageConfFile> -->
           <!-- <package>HelloWorld</package> -->
           <!-- <pathToFile>/local_disk/sherwood/RTT/HelloWorld_TestConfiguration.xml</pathToFile> -->
        <!-- </packageConfFile> -->
        <packageConfFile>
           <package>Simulation/Atlfast/TestAtlfast</package>
           <!-- <pathToFile>/afs/cern.ch/atlas/software/dist/11.0.0/Simulation/Atlfast/TestAtlfast/TestAtlfast-00-00-55/test/TestAtlfast_TestConfiguration.xml</pathToFile> -->
           <pathToFile>TESTSUITESCRATCH/xml/TestAtlfast_TestConfiguration.xml</pathToFile>
           <cmtdir>/afs/cern.ch/atlas/software/dist/11.0.0/Simulation/Atlfast/TestAtlfast/TestAtlfast-00-00-55/</cmtdir>
        </packageConfFile>
      </rttProvides>
      <!-- <localConfFiles> -->
         <!-- <package>Simulation/Atlfast/TestAtlfast</package> -->
      <!-- </localConfFiles> -->
      <!-- <installedConfFiles/> -->
   </confFileSrc>

   <!-- <packageAccept>HelloWorld</packageAccept> -->
   <!-- <packageVeto>TestAtlfast</packageVeto> -->
<!--   <testMode>NoNewRunDirs</testMode> -->
   <maxTime>
      <hours>1</hours>
   </maxTime>
   <!-- <rttKitTest/> -->
</rttconfig>
