=== rushioda/PIXELVALID_athena/athena/Tools/RunTimeTester/share/web/unifiedTestConfiguration.dtd
<!ELEMENT unifiedTestConfiguration ((doc?, atn,  kv?, rtt?) |
                                    (doc?, atn?, kv,  rtt?) |
                                    (doc?, atn?, kv?, rtt))>

<!ELEMENT classification ((none) | (displayClass, displayProcess+, displayComponent+))?>
<!ELEMENT displayClass (#PCDATA)>
<!ELEMENT displayProcess (#PCDATA)>
<!ELEMENT displayComponent (#PCDATA)>
<!ELEMENT none EMPTY>


<!ELEMENT atn         (classification?, TEST*)>
  <!ELEMENT TEST     (doc?, classification?, options_atn*, furtherOptions_atn*, timelimit*, author*, mailto*, prescript*, postscript*, package_atn*, rundir*, expectations*)>
  <!ATTLIST TEST   name       CDATA                    #IMPLIED>
  <!ATTLIST TEST   type       (script|athena|kv|rtt|makecheck)   #REQUIRED>
  <!ATTLIST TEST   suite      CDATA                    "general">
  <!ELEMENT options_atn     (#PCDATA | rttSpecs | kvSpecs)*>
      <!ELEMENT rttSpecs  ANY>
      <!ELEMENT kvSpecs   ANY>
  <!ELEMENT furtherOptions_atn (#PCDATA)>
  <!ELEMENT timelimit          (#PCDATA)>
  <!ELEMENT author             (#PCDATA)>
  <!ELEMENT mailto             (#PCDATA)>
  <!ELEMENT prescript          (#PCDATA)>
  <!ELEMENT postscript         (#PCDATA)>
  <!ELEMENT package_atn        (#PCDATA)>
  <!ELEMENT rundir             (#PCDATA)>
  <!ELEMENT expectations       (errorMessage*, warningMessage*, successMessage*, returnValue*)>
     <!ELEMENT errorMessage    (#PCDATA)>
     <!ELEMENT warningMessage  (#PCDATA)>
     <!ELEMENT successMessage  (#PCDATA)>
     <!ELEMENT returnValue     (#PCDATA)>

<!ELEMENT kv                (kvtest*)>
    <!ELEMENT kvtest (release,priority?,kvsuite,trf,desc,author?,version?,
                    inpath,infile,inpool,outpath,outfile,outntuple?,logfile,signature,copyfiles,checkfiles)>
    <!ATTLIST kvtest                name    CDATA #REQUIRED>
    <!ATTLIST kvtest                enabled CDATA #REQUIRED>

    <!ELEMENT release     (#PCDATA)> 
    <!ELEMENT priority    (#PCDATA)> 
    <!ELEMENT kvsuite       (#PCDATA)> 
    <!ELEMENT trf         (#PCDATA)> 
    <!ELEMENT desc        (#PCDATA)> 
    <!ELEMENT version     (#PCDATA)> 
    <!ELEMENT inpath      (#PCDATA)> 
    <!ELEMENT infile      (#PCDATA)> 
    <!ELEMENT inpool      (#PCDATA)> 
    <!ELEMENT outpath     (#PCDATA)> 
    <!ELEMENT outfile     (#PCDATA)> 
    <!ELEMENT outntuple   (#PCDATA)> 
    <!ELEMENT logfile     (#PCDATA)> 
    <!ELEMENT signature   (#PCDATA)> 
    <!ELEMENT copyfiles   (#PCDATA)> 
    <!ELEMENT checkfiles  (#PCDATA)> 


<!ELEMENT rtt              ((EMPTY) | (rttContactPerson*,mailto?,refRelease?, jobList, jobGroups?) | (jobGroups))?>
   <!ELEMENT refRelease    (#PCDATA)>   
   <!ELEMENT jobList       (classification?, athena*, rulechecker*, 
                            qametrics*,  kitvalidation*, rttmonitor*,
                            rttselftest*, jobTransform*)>
      <!ELEMENT athena     ( doc?, doclink?, (numberedOnly |  limitedNightlies)?, rttKitTestJob?, 
                            classification?, displayName?, commandLineFlags?, commandLineString?, preconfigOptions?, options, furtherOptions?,
                            package?, group, confederation?, 
                            queue?,  dataset*, dataset_info*, dq2*, asciiRefFile*, binRefFile*,
                            storeInDatabasePattern*, action*, monAction*, 
                            test*, athenaFlavour*)>

	 <!ELEMENT doc                    (#PCDATA)>
	 <!ELEMENT doclink                (#PCDATA)>
	 <!ELEMENT displayName            (#PCDATA)>
	 <!ELEMENT rttContactPerson       (#PCDATA)>
	 <!ELEMENT numberedOnly              EMPTY>
	 <!ELEMENT limitedNightlies          EMPTY>
	 <!ELEMENT limitedNightly         (nightly+)>
         <!ELEMENT rttKitTestJob          EMPTY>
         <!ELEMENT commandLineFlags       (#PCDATA)>
         <!ELEMENT commandLineString      (#PCDATA)>
         <!ELEMENT preconfigOptions       (#PCDATA)>
         <!ELEMENT options                (#PCDATA)>
          <!ELEMENT furtherOptions        (jobOptionItem+)>
             <!ELEMENT jobOptionItem      (#PCDATA)>
	 <!ELEMENT package                (#PCDATA)>
	 <!ELEMENT group                  (#PCDATA)>
	 <!ELEMENT confederation          (#PCDATA)>
	 <!ELEMENT queue                  (#PCDATA)>
	 <!ELEMENT nightly                (#PCDATA)>

 	 <!-- The old dataset tag -->
         <!ELEMENT dataset                  (#PCDATA)>	

 	 <!-- The new dataset tag along with the definition of its children elements -->

	 <!ELEMENT dataset_info                ((bytestream | dc2 | dc3 | jobTransformData), datasetName,datasetRepeat?)>
	 <!ELEMENT bytestream                 EMPTY>
	 <!ELEMENT dc2                        EMPTY>
	 <!ELEMENT dc3                        EMPTY>
	 <!ELEMENT jobTransformData           EMPTY>
	 <!ELEMENT datasetName            (#PCDATA)>
	 <!ELEMENT datasetRepeat          (#PCDATA)>
         <!ELEMENT dq2                    (dq2site, dq2dataset,datatype, dq2file+)>
         <!ELEMENT dq2site                (#PCDATA)>
         <!ELEMENT dq2dataset             (#PCDATA)>
         <!ELEMENT datatype               (#PCDATA)>
         <!ELEMENT dq2file                (#PCDATA)>
	 <!ELEMENT asciiRefFile           (#PCDATA)>
	 <!ELEMENT storeInDatabasePattern (#PCDATA)>
	 <!ELEMENT athenaFlavour          (#PCDATA)>

      <!ELEMENT rulechecker ( (numberedOnly | limitedNightlies)?, 
                             package, queue)>
      <!ELEMENT qametrics   ( (numberedOnly | limitedNightlies)?,
                             package, queue)>
      <!ELEMENT kitvalidation ((EMPTY) | ( (numberedOnly | limitedNightlies)?, queue))?>
      <!ELEMENT rttmonitor EMPTY>
      <!ELEMENT rttselftest EMPTY>
      <!ELEMENT jobTransform ((numberedOnly |  limitedNightlies)?, 
                              doc?, doclink?, classification?, rttKitTestJob?, displayName?, jobTransformJobName, 
                              jobTransformCmd, group, dataset_info*, queue?)>

         <!ELEMENT jobTransformJobName (#PCDATA)>
         <!ELEMENT jobTransformCmd (#PCDATA)>


   <!ELEMENT jobGroups (jobGroup+)>
      <!ELEMENT jobGroup (keepFilePattern*,   asciiRefFile*, 
                          binRefFile*,        storeInDatabasePattern*, 
                          checker*,           
                          postScript*,        auxFilePattern*, 
                          action*,            monAction*,test*,   stringToFile*,     
                          summary*,           logChecker*)>

            <!ELEMENT keepFilePattern (#PCDATA)>
	    <!ELEMENT binRefFile      (#PCDATA)>
            <!ELEMENT checker         ((searchString*, vetoString*) | (comparisonType?))>
	       <!ELEMENT searchString     (#PCDATA)>
	       <!ELEMENT vetoString       (#PCDATA)>
               <!ELEMENT comparisonType   (#PCDATA)>
            <!ELEMENT postScript          EMPTY>
	    <!ELEMENT auxFilePattern      (#PCDATA)>
            <!ELEMENT action             (modulename,testname, arg*, listarg*)>
            <!ELEMENT monAction          (modulename,testname, arg*, listarg*)>
            <!ELEMENT test               (modulename,testname, arg*, listarg*)>
               <!ELEMENT modulename       (#PCDATA)>
	       <!ELEMENT testname         (#PCDATA)>
               <!ELEMENT arg              (argname, argvalue)>
	          <!ELEMENT argname       (#PCDATA)>
		  <!ELEMENT argvalue      (#PCDATA)>
               <!ELEMENT listarg          (listargname, listargvalue+)>
	          <!ELEMENT listargname   (#PCDATA)>
		  <!ELEMENT listargvalue  (#PCDATA)>
            <!ELEMENT stringToFile        (line+)>
	       <!ELEMENT line             (#PCDATA)>
            <!ELEMENT logChecker          ((searchString+, vetoString*) | 
	                                   (searchString*, vetoString+))>
            <!ELEMENT summary             (#PCDATA)>

<!ATTLIST rtt               xmlns  CDATA #REQUIRED>
<!ATTLIST jobGroup          name   CDATA #REQUIRED>
<!ATTLIST jobGroup          parent CDATA #REQUIRED>
<!ATTLIST class             name   CDATA #REQUIRED>
<!ATTLIST action            position  CDATA "">
<!ATTLIST test              position  CDATA "">
<!ATTLIST keepFilePattern   info   CDATA "">
<!ATTLIST keepFilePattern   displayColor   CDATA "black">
<!ATTLIST checker           class  CDATA #REQUIRED>
<!ATTLIST logChecker        class  CDATA #REQUIRED>
<!ATTLIST postScript        class  CDATA #REQUIRED>
<!ATTLIST stringToFile      file   CDATA #REQUIRED>

=== rushioda/PIXELVALID_athena/athena/LArCalorimeter/LArExample/LArCalibProcessing/test/LArCalibProcessing_TestConfiguration.xml
<?xml version="1.0"?>
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">

<unifiedTestConfiguration>

<atn>
  <TEST name="LArCalib_Pedestal" type="athena" suite="LArElecCalib">
     <options_atn> -c 'doMonitoring=False; runAccumulator=False; doLArCalibDataQuality=True; GainList=["HIGH"]; PartitionType="EMB"; Partition="EB-EMBA"; PartitionTypeGeneric="EMBPS"; RunNumberList=[174585]; RunNumberFlag=int(RunNumberList[0]); InputDir=" "; FullFileName=["/afs/cern.ch/user/l/larcalib/w0/Test/data11_calib.00174585.calibration_LArElec-Pedestal-7s-High-BarrelPS.daq.RAW._lb0000._EB-EMBA._0001.data"]; GroupingType="ExtendedSubDetector" ' LArCalibProcessing/UseLArExtendedSubDetGrouping.py  LArCalibProcessing/LArCalib_PedestalAutoCorr_jobOptions.py LArCalibProcessing/LArCalib_PedestalAutoCorr_testing.py</options_atn>
     <timelimit>30</timelimit>
     <author> Pavol Strizenec </author>
     <mailto> pavol@mail.cern.ch </mailto>
     <expectations>
     </expectations>
  </TEST>
  <TEST name="LArCalib_Ramp" type="athena" suite="LArElecCalib">
     <options_atn> -c 'doMonitoring=False; doLArCalibDataQuality=True; CorrectBadChannels=True; ApplyAdHocCorrection=False; GainList=["HIGH"]; PartitionType="EMB"; Partition="EB-EMBA"; PartitionTypeGeneric="EMBPS"; RunNumberList=[174586]; RunNumberFlag=int(RunNumberList[0]); InputDir=" "; FullFileName=["/afs/cern.ch/user/l/larcalib/w0/Test/data11_calib.00174586.calibration_LArElec-Ramp-7s-High-BarrelPS.daq.RAW._lb0000._EB-EMBA._0001.data"]; GroupingType="ExtendedSubDetector" ' LArCalibProcessing/UseLArExtendedSubDetGrouping.py  LArCalibProcessing/LArCalib_Ramp_jobOptions.py LArCalibProcessing/LArCalib_Ramp_testing.py</options_atn>
     <timelimit>30</timelimit>
     <author> Pavol Strizenec </author>
     <mailto> pavol@mail.cern.ch </mailto>
     <expectations>
     </expectations>
  </TEST>
</atn>

</unifiedTestConfiguration>

=== rushioda/PIXELVALID_athena/athena/Control/AthenaExamples/TBBExamples/test/TBBExamples_TestConfiguration.xml
<?xml version="1.0"?>
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">

<unifiedTestConfiguration>
  <atn>
     <TEST name="TBBExamples" type="athena" suite="Examples">
        <options_atn>TBBExamples/HelloParForOptions.py</options_atn>
        <timelimit>2</timelimit>
        <author> Paolo Calafiura </author>
        <mailto> pcalafiura@lbl.gov </mailto>
        <expectations>
           <errorMessage>FAILURE (ERROR)</errorMessage>
           <successMessage></successMessage>
           <returnValue>0</returnValue>
        </expectations>
     </TEST>
   </atn>
</unifiedTestConfiguration>

=== rushioda/PIXELVALID_athena/athena/AtlasTest/DatabaseTest/IOVDbTestAlg/test/IOVDbTestAlg_TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">

<unifiedTestConfiguration>

<atn>
   <TEST name="IOVDbTestAlg" type="makecheck" suite="Examples">
      <author> RD Schaffer </author>
      <mailto> R.D.Schaffer@cern.ch </mailto>
      <timelimit>10</timelimit>
      <expectations>
         <errorMessage>post.sh> ERROR:</errorMessage>
         <successMessage>post.sh> OK:</successMessage>   
         <returnValue>0</returnValue>
      </expectations>
   </TEST>
</atn>

</unifiedTestConfiguration>

=== rushioda/PIXELVALID_athena/athena/Calorimeter/CaloExample/CaloSimEx/test/CaloSimEx_TestConfiguration.xml
<?xml version="1.0"?>
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">

<unifiedTestConfiguration>

<atn>
<TEST name="CaloSimEx" type="athena" suite="CaloSimEx">
    <options_atn>CaloSimEx/CaloSimEx.py</options_atn>
    <timelimit>20</timelimit>
    <author>Emmanuel Le Guirriec</author>    
    <mailto>guirriec@cern.ch,toth@cppm.in2p3.fr</mailto>
    <package_atn>Calorimeter/CaloExample/CaloSimEx</package_atn>
    <expectations>
       <successMessage>Finalized successfully</successMessage>
    </expectations>
</TEST>
</atn>

<kv/>		

<rtt xmlns="http://www.hep.ucl.ac.uk/atlas/AtlasTesting/rtt">

<rttContactPerson>Emmanuel Le Guirriec</rttContactPerson>
<mailto>guirriec@cern.ch,toth@cppm.in2p3.fr</mailto>

<refRelease>10.0.1</refRelease>
   
<jobList>


  <classification>
       <displayClass>Development</displayClass>
       <displayProcess>Simul</displayProcess>
       <displayComponent>Det-LAr</displayComponent>
  </classification>

  <athena userJobId="CaloSimEx_RTT">
       <doc>single electrons,5 GeV,ATLAS_CSC_01_00_00,https://twiki.cern.ch/twiki/bin/view/Atlas/CaloIntegration</doc>
       <options>CaloSimEx_RTT.py</options>
       <package>Calorimeter/CaloExample/CaloSimEx</package>
       <group>CaloSimEx</group>
       <queue>medium</queue>
   </athena>

</jobList>
      
<jobGroups>
       <jobGroup name="CaloSimEx" parent="RTT:Athena">
       </jobGroup>
</jobGroups>

</rtt>

</unifiedTestConfiguration>
