=== rushioda/PIXELVALID_athena/athena/Tools/RunTimeTester/share/web/unifiedTestConfiguration.dtd
<!ELEMENT unifiedTestConfiguration ((doc?, atn,  kv?, rtt?) |
                                    (doc?, atn?, kv,  rtt?) |
                                    (doc?, atn?, kv?, rtt))>

<!ELEMENT classification ((none) | (displayClass, displayProcess+, displayComponent+))?>
<!ELEMENT displayClass (#PCDATA)>
<!ELEMENT displayProcess (#PCDATA)>
<!ELEMENT displayComponent (#PCDATA)>
<!ELEMENT none EMPTY>


<!ELEMENT atn         (classification?, TEST*)>
  <!ELEMENT TEST     (doc?, classification?, options_atn*, furtherOptions_atn*, timelimit*, author*, mailto*, prescript*, postscript*, package_atn*, rundir*, expectations*)>
  <!ATTLIST TEST   name       CDATA                    #IMPLIED>
  <!ATTLIST TEST   type       (script|athena|kv|rtt|makecheck)   #REQUIRED>
  <!ATTLIST TEST   suite      CDATA                    "general">
  <!ELEMENT options_atn     (#PCDATA | rttSpecs | kvSpecs)*>
      <!ELEMENT rttSpecs  ANY>
      <!ELEMENT kvSpecs   ANY>
  <!ELEMENT furtherOptions_atn (#PCDATA)>
  <!ELEMENT timelimit          (#PCDATA)>
  <!ELEMENT author             (#PCDATA)>
  <!ELEMENT mailto             (#PCDATA)>
  <!ELEMENT prescript          (#PCDATA)>
  <!ELEMENT postscript         (#PCDATA)>
  <!ELEMENT package_atn        (#PCDATA)>
  <!ELEMENT rundir             (#PCDATA)>
  <!ELEMENT expectations       (errorMessage*, warningMessage*, successMessage*, returnValue*)>
     <!ELEMENT errorMessage    (#PCDATA)>
     <!ELEMENT warningMessage  (#PCDATA)>
     <!ELEMENT successMessage  (#PCDATA)>
     <!ELEMENT returnValue     (#PCDATA)>

<!ELEMENT kv                (kvtest*)>
    <!ELEMENT kvtest (release,priority?,kvsuite,trf,desc,author?,version?,
                    inpath,infile,inpool,outpath,outfile,outntuple?,logfile,signature,copyfiles,checkfiles)>
    <!ATTLIST kvtest                name    CDATA #REQUIRED>
    <!ATTLIST kvtest                enabled CDATA #REQUIRED>

    <!ELEMENT release     (#PCDATA)> 
    <!ELEMENT priority    (#PCDATA)> 
    <!ELEMENT kvsuite       (#PCDATA)> 
    <!ELEMENT trf         (#PCDATA)> 
    <!ELEMENT desc        (#PCDATA)> 
    <!ELEMENT version     (#PCDATA)> 
    <!ELEMENT inpath      (#PCDATA)> 
    <!ELEMENT infile      (#PCDATA)> 
    <!ELEMENT inpool      (#PCDATA)> 
    <!ELEMENT outpath     (#PCDATA)> 
    <!ELEMENT outfile     (#PCDATA)> 
    <!ELEMENT outntuple   (#PCDATA)> 
    <!ELEMENT logfile     (#PCDATA)> 
    <!ELEMENT signature   (#PCDATA)> 
    <!ELEMENT copyfiles   (#PCDATA)> 
    <!ELEMENT checkfiles  (#PCDATA)> 


<!ELEMENT rtt              ((EMPTY) | (rttContactPerson*,mailto?,refRelease?, jobList, jobGroups?) | (jobGroups))?>
   <!ELEMENT refRelease    (#PCDATA)>   
   <!ELEMENT jobList       (classification?, athena*, rulechecker*, 
                            qametrics*,  kitvalidation*, rttmonitor*,
                            rttselftest*, jobTransform*)>
      <!ELEMENT athena     ( doc?, doclink?, (numberedOnly |  limitedNightlies)?, rttKitTestJob?, 
                            classification?, displayName?, commandLineFlags?, commandLineString?, preconfigOptions?, options, furtherOptions?,
                            package?, group, confederation?, 
                            queue?,  dataset*, dataset_info*, dq2*, asciiRefFile*, binRefFile*,
                            storeInDatabasePattern*, action*, monAction*, 
                            test*, athenaFlavour*)>

	 <!ELEMENT doc                    (#PCDATA)>
	 <!ELEMENT doclink                (#PCDATA)>
	 <!ELEMENT displayName            (#PCDATA)>
	 <!ELEMENT rttContactPerson       (#PCDATA)>
	 <!ELEMENT numberedOnly              EMPTY>
	 <!ELEMENT limitedNightlies          EMPTY>
	 <!ELEMENT limitedNightly         (nightly+)>
         <!ELEMENT rttKitTestJob          EMPTY>
         <!ELEMENT commandLineFlags       (#PCDATA)>
         <!ELEMENT commandLineString      (#PCDATA)>
         <!ELEMENT preconfigOptions       (#PCDATA)>
         <!ELEMENT options                (#PCDATA)>
          <!ELEMENT furtherOptions        (jobOptionItem+)>
             <!ELEMENT jobOptionItem      (#PCDATA)>
	 <!ELEMENT package                (#PCDATA)>
	 <!ELEMENT group                  (#PCDATA)>
	 <!ELEMENT confederation          (#PCDATA)>
	 <!ELEMENT queue                  (#PCDATA)>
	 <!ELEMENT nightly                (#PCDATA)>

 	 <!-- The old dataset tag -->
         <!ELEMENT dataset                  (#PCDATA)>	

 	 <!-- The new dataset tag along with the definition of its children elements -->

	 <!ELEMENT dataset_info                ((bytestream | dc2 | dc3 | jobTransformData), datasetName,datasetRepeat?)>
	 <!ELEMENT bytestream                 EMPTY>
	 <!ELEMENT dc2                        EMPTY>
	 <!ELEMENT dc3                        EMPTY>
	 <!ELEMENT jobTransformData           EMPTY>
	 <!ELEMENT datasetName            (#PCDATA)>
	 <!ELEMENT datasetRepeat          (#PCDATA)>
         <!ELEMENT dq2                    (dq2site, dq2dataset,datatype, dq2file+)>
         <!ELEMENT dq2site                (#PCDATA)>
         <!ELEMENT dq2dataset             (#PCDATA)>
         <!ELEMENT datatype               (#PCDATA)>
         <!ELEMENT dq2file                (#PCDATA)>
	 <!ELEMENT asciiRefFile           (#PCDATA)>
	 <!ELEMENT storeInDatabasePattern (#PCDATA)>
	 <!ELEMENT athenaFlavour          (#PCDATA)>

      <!ELEMENT rulechecker ( (numberedOnly | limitedNightlies)?, 
                             package, queue)>
      <!ELEMENT qametrics   ( (numberedOnly | limitedNightlies)?,
                             package, queue)>
      <!ELEMENT kitvalidation ((EMPTY) | ( (numberedOnly | limitedNightlies)?, queue))?>
      <!ELEMENT rttmonitor EMPTY>
      <!ELEMENT rttselftest EMPTY>
      <!ELEMENT jobTransform ((numberedOnly |  limitedNightlies)?, 
                              doc?, doclink?, classification?, rttKitTestJob?, displayName?, jobTransformJobName, 
                              jobTransformCmd, group, dataset_info*, queue?)>

         <!ELEMENT jobTransformJobName (#PCDATA)>
         <!ELEMENT jobTransformCmd (#PCDATA)>


   <!ELEMENT jobGroups (jobGroup+)>
      <!ELEMENT jobGroup (keepFilePattern*,   asciiRefFile*, 
                          binRefFile*,        storeInDatabasePattern*, 
                          checker*,           
                          postScript*,        auxFilePattern*, 
                          action*,            monAction*,test*,   stringToFile*,     
                          summary*,           logChecker*)>

            <!ELEMENT keepFilePattern (#PCDATA)>
	    <!ELEMENT binRefFile      (#PCDATA)>
            <!ELEMENT checker         ((searchString*, vetoString*) | (comparisonType?))>
	       <!ELEMENT searchString     (#PCDATA)>
	       <!ELEMENT vetoString       (#PCDATA)>
               <!ELEMENT comparisonType   (#PCDATA)>
            <!ELEMENT postScript          EMPTY>
	    <!ELEMENT auxFilePattern      (#PCDATA)>
            <!ELEMENT action             (modulename,testname, arg*, listarg*)>
            <!ELEMENT monAction          (modulename,testname, arg*, listarg*)>
            <!ELEMENT test               (modulename,testname, arg*, listarg*)>
               <!ELEMENT modulename       (#PCDATA)>
	       <!ELEMENT testname         (#PCDATA)>
               <!ELEMENT arg              (argname, argvalue)>
	          <!ELEMENT argname       (#PCDATA)>
		  <!ELEMENT argvalue      (#PCDATA)>
               <!ELEMENT listarg          (listargname, listargvalue+)>
	          <!ELEMENT listargname   (#PCDATA)>
		  <!ELEMENT listargvalue  (#PCDATA)>
            <!ELEMENT stringToFile        (line+)>
	       <!ELEMENT line             (#PCDATA)>
            <!ELEMENT logChecker          ((searchString+, vetoString*) | 
	                                   (searchString*, vetoString+))>
            <!ELEMENT summary             (#PCDATA)>

<!ATTLIST rtt               xmlns  CDATA #REQUIRED>
<!ATTLIST jobGroup          name   CDATA #REQUIRED>
<!ATTLIST jobGroup          parent CDATA #REQUIRED>
<!ATTLIST class             name   CDATA #REQUIRED>
<!ATTLIST action            position  CDATA "">
<!ATTLIST test              position  CDATA "">
<!ATTLIST keepFilePattern   info   CDATA "">
<!ATTLIST keepFilePattern   displayColor   CDATA "black">
<!ATTLIST checker           class  CDATA #REQUIRED>
<!ATTLIST logChecker        class  CDATA #REQUIRED>
<!ATTLIST postScript        class  CDATA #REQUIRED>
<!ATTLIST stringToFile      file   CDATA #REQUIRED>

=== rushioda/PIXELVALID_athena/athena/InnerDetector/InDetValidation/InDetGeometryValidation/test/InDetGeometryValidation_TestConfiguration.xml
<?xml version="1.0"?>
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">   
<unifiedTestConfiguration> 
<atn>
   <TEST name="InDetGeometryValidation" type="script" suite="Examples">
     <options_atn>InnerDetector/InDetValidation/InDetGeometryValidation/test/InDetGeometryValidation_Test.sh</options_atn>
     <author>Atlas Developer</author>
     <mailto>hays@physics.ox.ac.uk</mailto>
      <expectations>
         <returnValue>0</returnValue>
      </expectations>
   </TEST>

   <TEST name="InDetGeometryValidation" type="athena" suite="Examples">
     <options_atn>InDetGeometryValidation/ReadSiDetectorElements_jobOptions.py</options_atn>
     <timelimit>3</timelimit>
     <author>Atlas Developer</author>
     <mailto>hays@physics.ox.ac.uk</mailto>
      <expectations>
         <errorMessage>ERROR</errorMessage>
         <returnValue>0</returnValue>
      </expectations>
   </TEST>

   <TEST name="InDetGeometryValidation" type="athena" suite="Examples">
     <options_atn>InDetGeometryValidation/ReadTRT_DetectorElements_jobOptions.py</options_atn>
     <timelimit>3</timelimit>
     <author>Atlas Developer</author>
     <mailto>hays@physics.ox.ac.uk</mailto>
      <expectations>
         <errorMessage>ERROR</errorMessage>
         <returnValue>0</returnValue>
      </expectations>
   </TEST>

</atn>
</unifiedTestConfiguration>

=== rushioda/PIXELVALID_athena/athena/MuonSpectrometer/MuonAlignment/MuonAlignExample/test/MuonAlignExample_TestConfiguration.xml
<?xml version="1.0"?>  
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">

<unifiedTestConfiguration>
<atn/>
<kv/>
<rtt xmlns="http://www.hep.ucl.ac.uk/atlas/AtlasTesting/rtt" >
  <rttContactPerson>Robert Harrington (roberth@NOSPAMbu.edu)</rttContactPerson>
  <mailto>roberth@NOSPAMbu.edu</mailto>
  <refRelease></refRelease>
  
  <jobList>
    <classification>
      <displayClass>OfflineValidation</displayClass>
      <displayProcess>Reco</displayProcess>
      <displayComponent>Det-Muon</displayComponent>
    </classification>
    
    <athena userJobId="MuonAlign_L3EC">
      <doc>Muon Alignment test</doc>
      <displayName>MdtGlobalChi2AlignAlgs_Reco_Test</displayName>
      <options>MuonAlignExample/runargs.ESDtoESD.py</options>
      <package>MuonSpectrometer/MuonAlignment/MuonAlignExample</package>
      <group>MuonAlignExample</group>
      <queue>medium</queue>
      <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/det-muon/Bytestream2010/MuonBytestreamRun155697_selectedCbMu10Events_rec15.6.10.ESD.pool.root</dataset>
    </athena>
    
  </jobList>

  <jobGroups>
    <jobGroup name="AthenaMuonAlignExample" parent="Athena">
      <keepFilePattern> *.txt </keepFilePattern>
      <keepFilePattern> *.root </keepFilePattern>
      <keepFilePattern> *.ps </keepFilePattern>
      <keepFilePattern> *.gif </keepFilePattern>
      <keepFilePattern> *.log </keepFilePattern>
      <keepFilePattern> *.C </keepFilePattern>
      <keepFilePattern> *.py </keepFilePattern>
    </jobGroup>
  </jobGroups>
</rtt>
</unifiedTestConfiguration>

=== rushioda/PIXELVALID_athena/athena/Trigger/TrigValidation/TrigBjetValidation/test/TrigBjetValidation_TestConfiguration.xml
<?xml version="1.0"?>
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">
<unifiedTestConfiguration>

  <atn/>
  <kv/>

   <rtt xmlns="http://www.hep.ucl.ac.uk/atlas/AtlasTesting/rtt">
      <mailto>Andrea.Coccaro@ge.infn.it, Fabrizio.Parodi@ge.infn.it</mailto>
      <refRelease>15.4.0</refRelease>

      <jobList>

      <classification>
         <displayClass>OfflineValidation</displayClass>
         <displayProcess>Reco</displayProcess>
         <displayComponent>Trig-Other</displayComponent>
      </classification>

         <athena userJobId='TrigBjetValidation_5200'>
            <doc>Tests Bjet slice using ttbar misaligned data</doc>
            <displayName>BjetSlice</displayName>
	    <commandLineFlags>DetDescrVersion="ATLAS-GEO-06-00-00";EventMax=2000;</commandLineFlags>
            <options>TrigBjetValidation_RTT_topOptions</options>
            <package>Trigger/TrigValidation/TrigBjetValidation</package>
            <group>TrigBjetValidation</group>
            <queue>medium</queue>
	    <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/proj-sit/coccaro/RTT/RTTdata/valid1.105200.T1_McAtNlo_Jimmy.digit.RDO.e380_s553_tid068538/RDO.068538._00049.pool.root.3</dataset>
	    <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/proj-sit/coccaro/RTT/RTTdata/valid1.105200.T1_McAtNlo_Jimmy.digit.RDO.e380_s553_tid068538/RDO.068538._00056.pool.root.3</dataset>
	    <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/proj-sit/coccaro/RTT/RTTdata/valid1.105200.T1_McAtNlo_Jimmy.digit.RDO.e380_s553_tid068538/RDO.068538._00142.pool.root.4</dataset>
	    <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/proj-sit/coccaro/RTT/RTTdata/valid1.105200.T1_McAtNlo_Jimmy.digit.RDO.e380_s553_tid068538/RDO.068538._00316.pool.root.4</dataset>
	    <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/proj-sit/coccaro/RTT/RTTdata/valid1.105200.T1_McAtNlo_Jimmy.digit.RDO.e380_s553_tid068538/RDO.068538._00453.pool.root.2</dataset>
	    <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/proj-sit/coccaro/RTT/RTTdata/valid1.105200.T1_McAtNlo_Jimmy.digit.RDO.e380_s553_tid068538/RDO.068538._00574.pool.root.3</dataset>
	    <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/proj-sit/coccaro/RTT/RTTdata/valid1.105200.T1_McAtNlo_Jimmy.digit.RDO.e380_s553_tid068538/RDO.068538._00587.pool.root.1</dataset>
	    <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/proj-sit/coccaro/RTT/RTTdata/valid1.105200.T1_McAtNlo_Jimmy.digit.RDO.e380_s553_tid068538/RDO.068538._00758.pool.root.3</dataset>
	    <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/proj-sit/coccaro/RTT/RTTdata/valid1.105200.T1_McAtNlo_Jimmy.digit.RDO.e380_s553_tid068538/RDO.068538._00761.pool.root.3</dataset>
	    <dataset>/castor/cern.ch/atlas/atlascerngroupdisk/proj-sit/coccaro/RTT/RTTdata/valid1.105200.T1_McAtNlo_Jimmy.digit.RDO.e380_s553_tid068538/RDO.068538._00956.pool.root.1</dataset>

            <test>
                <modulename>RttLibraryTools</modulename>
                <testname>ExeRunner</testname>
                <arg>
                    <argname>exeName</argname>
                    <argvalue>TrigBjetValidation_Histos</argvalue>
                </arg>
            </test>

	 </athena>

      </jobList>

      <jobGroups>

         <jobGroup name="AthenaTrigBjetValidation" parent="Athena">

            <keepFilePattern displayColor="blue" info="CBNTAA">ntuple*.root</keepFilePattern>
            <keepFilePattern displayColor="blue">TrigBjetValidation_Histograms*.root</keepFilePattern>
            <keepFilePattern displayColor="blue">expert-monitoring.root</keepFilePattern>
            <keepFilePattern displayColor="blue">*.png</keepFilePattern>
            <keepFilePattern>*.pool.root</keepFilePattern>

	    <auxFilePattern>TrigBjetValidation_Histos.cpp</auxFilePattern>

         </jobGroup>
      </jobGroups>
   </rtt>

</unifiedTestConfiguration>

=== rushioda/PIXELVALID_athena/athena/Generators/HepMCAnalysis_i/setup/models/TestConfiguration_skelethon.xml
<?xml version="1.0"?> 
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">

<unifiedTestConfiguration> 
  <!-- RTT tests -->
  <rtt xmlns="http://www.hep.ucl.ac.uk/atlas/AtlasTesting/rtt"> 
    <rttContactPerson>Stefano Camarda</rttContactPerson>
    <!--    <mailto>stefano.camarda@cern.ch</mailto> -->

    <!-- sj: This reference release was chosen until there is a stable release where it is possible to import "evgenConfig" -->
    <refRelease>rel_2, 2012-04-17</refRelease>

    <jobList>
      <classification>
        <displayClass>OfflineValidation</displayClass>
        <displayProcess>EvGen</displayProcess>
        <displayComponent>Athena-Core</displayComponent>
      </classification>
    </jobList>

    <jobGroups>
      <jobGroup name="HepMCAnalysis_i" parent="Athena">
	<!--Files produced by the job and that I want to keep in the results dir-->
        <keepFilePattern info="xml files" displayColor="blue">*.xml</keepFilePattern>
        <keepFilePattern info="python scripts" displayColor="red">*.py</keepFilePattern>
        <keepFilePattern info="txt files" displayColor="blue">*.txt</keepFilePattern>
        <keepFilePattern info="log files" displayColor="blue">*.log</keepFilePattern>
<!--        <keepFilePattern info="root scripts" displayColor="green">*.C</keepFilePattern> -->
<!--        <keepFilePattern info="root files" displayColor="grey">*.root</keepFilePattern> -->
<!--        <keepFilePattern info="java scripts" displayColor="green">*.jar</keepFilePattern> -->
        <keepFilePattern info="all log files" displayColor="blue">*log*</keepFilePattern>
	<!--Files that the post job needs-->
<!-- not really needed...
        <auxFilePattern>*.py</auxFilePattern>
        <auxFilePattern>*.xml</auxFilePattern>
        <auxFilePattern>*.txt</auxFilePattern>
-->        
        <testToRemove>
          <jobGroupName>RTT:Top</jobGroupName>
          <testidentifier>CheckFileRunner0</testidentifier>
        </testToRemove>
      </jobGroup>
    </jobGroups>
  
  </rtt> <!-- eof RTT tests -->
</unifiedTestConfiguration>

=== rushioda/PIXELVALID_athena/athena/Trigger/TrigValidation/TrigAnalysisTest/test/TrigAnalysisTest_AthAnalysisBaseTestConfiguration.xml
<?xml version="1.0"?> 
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd"> 
<!-- NB validate this file here before committing to svn:
 python /afs/cern.ch/user/r/rtt/public/xmlvalidate.py TrigAnalysisTest_AthAnalysisBaseTestConfiguration.xml
 -->
<unifiedTestConfiguration>
    
	<atn>
	   <TEST name="TriggersFired_atn" type="athena" suite="TriggerDecisionToolTest">
	      <options_atn>TrigAnalysisTest/TriggersFiredTest_jobOptions.py</options_atn>
	      <timelimit>30</timelimit>
	      <author>Javier Montejo</author>
	      <mailto>jmontejo@cern.ch</mailto>
			 <package_atn>Trigger/TrigValidation/TrigAnalysisTest</package_atn>
	      <expectations>
	         <errorMessage>FAILURE </errorMessage>
	         <returnValue>0</returnValue>
	      </expectations>
	   </TEST>


	   <TEST name="Run1xAODValidation_atn" type="athena" suite="TriggerDecisionToolTest">
	      <options_atn>TrigAnalysisTest/ValidateRun1BStoxAOD_jobOptions.py</options_atn>
	      <timelimit>30</timelimit>
	      <author>Oleg Kuprash</author>
	      <mailto>oleg.kuprash@cern.ch</mailto>
			 <package_atn>Trigger/TrigValidation/TrigAnalysisTest</package_atn>
	      <expectations>
	         <errorMessage>FAILURE </errorMessage>
	         <returnValue>0</returnValue>
	      </expectations>
	   </TEST>
	</atn>


</unifiedTestConfiguration>

=== rushioda/PIXELVALID_athena/athena/ReleaseTests/test/ReleaseTests_TestConfiguration.xml
<?xml version="1.0"?>
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">

<unifiedTestConfiguration>
  
  <atn>
    <TEST name="ReleaseTests" type="script" suite="Examples">
      <options_atn>
	${ATN_PACKAGE}/bin/testSelectionXML.py
      </options_atn>
      <timelimit>60</timelimit>
      <author>Rolf Seuster</author>
      <prescript>rm -f $ATN_WORK_AREA/*</prescript>
      <expectations>
	<returnValue>0</returnValue>
      </expectations>
    </TEST>
  </atn>
  
</unifiedTestConfiguration>

=== rushioda/PIXELVALID_athena/athena/Control/AthenaExamples/AthExHelloWorld/test/AthExHelloWorld_TestConfiguration.xml
<?xml version="1.0"?>
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">

<unifiedTestConfiguration>
  <atn>
     <TEST name="HelloWorld" type="athena" suite="Examples">
        <options_atn>AthExHelloWorld/HelloWorld_ATN.py</options_atn>
        <timelimit>2</timelimit>
        <author> Alex Undrus </author>
        <mailto> undrus@bnl.gov </mailto>
        <expectations>
           <errorMessage>FAILURE (ERROR)</errorMessage>
           <successMessage>FATAL A FATAL</successMessage>
           <returnValue>0</returnValue>
        </expectations>
     </TEST>
   </atn>
   <kv/>
   <rtt xmlns="http://www.hep.ucl.ac.uk/atlas/AtlasTesting/rtt">

      <rttContactPerson>Paolo Calafiura</rttContactPerson>
      <mailto>pcalafiura@lbl.gov</mailto>
      <refRelease>13.0.0</refRelease>
      
      <jobList>

      <classification>
         <displayClass>OfflineValidation</displayClass>
         <displayProcess>Core</displayProcess>
         <displayComponent>Athena-Core</displayComponent>
      </classification>

         <athena userJobId="helloworld">
            <doc> Run Athena HelloWorld example </doc>
            <options>AthExHelloWorld/HelloWorldOptions</options>
            <package>Control/AthenaExamples/AthExHelloWorld</package>
            <group>HelloWorld</group>
            <queue>short</queue>
         </athena>
      </jobList>

      <jobGroups>
         <jobGroup name="AthenaHelloWorld" parent="Athena"/>
      </jobGroups>
   </rtt>
</unifiedTestConfiguration>

=== rushioda/PIXELVALID_athena/athena/AtlasTest/DatabaseTest/AthenaPoolMultiTest/test/AthenaPoolMultiTest_TestConfiguration.xml
<?xml version="1.0"?>
<!DOCTYPE unifiedTestConfiguration SYSTEM "http://www.hep.ucl.ac.uk/atlas/AtlasTesting/DTD/unifiedTestConfiguration.dtd">

<unifiedTestConfiguration>

<atn>
   <TEST name="AthenaPoolMultiTest" type="makecheck" suite="AthenaPoolMultiTest-Core">
      <timelimit>15</timelimit>
      <author> Jack Cranshaw </author>
      <mailto> cranshaw@anl.gov </mailto>
      <expectations>
         <errorMessage> FAILURE</errorMessage>
         <errorMessage> ERROR</errorMessage>
         <successMessage> check ok</successMessage>   
         <returnValue>0</returnValue>
      </expectations>
   </TEST>
</atn>
</unifiedTestConfiguration>
