=== rushioda/PIXELVALID_athena/athena/Database/CoolRunQuery/html/LumiRangeCollection.dtd
<!ELEMENT LumiRangeCollection (NamedLumiRange*)>

<!ELEMENT NamedLumiRange (Name?, Version?, Metadata*, LumiBlockCollection*)>

<!ELEMENT Metadata (#PCDATA|Stream)*>
<!ATTLIST Metadata Name CDATA #REQUIRED>

<!ELEMENT Stream EMPTY>
<!ATTLIST Stream
    Name CDATA #REQUIRED
    TotalNumOfEvents CDATA #IMPLIED
    NumOfSelectedEvents CDATA #IMPLIED
>

<!ELEMENT LumiBlockCollection (Run, LBRange*)>

<!ELEMENT Name (#PCDATA)>
<!ELEMENT Version (#PCDATA)>
<!ELEMENT Run (#PCDATA)>
<!ATTLIST Run PrescaleRD0 CDATA #IMPLIED>
<!ATTLIST Run PrescaleRD1 CDATA #IMPLIED>
<!ELEMENT LBRange EMPTY>
<!ATTLIST LBRange Start CDATA #REQUIRED> 
<!ATTLIST LBRange End CDATA #IMPLIED>

=== rushioda/PIXELVALID_athena/athena/LumiBlock/LumiBlockComps/run/grl1.xml
<?xml version="1.0"?>
<!DOCTYPE LumiRangeCollection SYSTEM "http://atlas-runquery.cern.ch/LumiRangeCollection.dtd">
<!--This document is created by GoodRunsListWriter. Ask Max Baak for details.-->
<LumiRangeCollection>
  <NamedLumiRange>
    <Name>grl1</Name>
    <Version>1</Version>
    <LumiBlockCollection>
      <Run>108175</Run>
      <LBRange Start="3472" End="3472"/>
      <LBRange Start="3475" End="3488"/>
      <LBRange Start="3490" End="3502"/>
      <LBRange Start="3504" End="3510"/>
      <LBRange Start="3518" End="3518"/>
      <LBRange Start="3521" End="3533"/>
    </LumiBlockCollection>
  </NamedLumiRange>
</LumiRangeCollection>
